//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_oculus p_oculus;
        
        private static SteamVR_Input_ActionSet_tracker p_tracker;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_oculus oculus
        {
            get
            {
                return SteamVR_Actions.p_oculus.GetCopy<SteamVR_Input_ActionSet_oculus>();
            }
        }
        
        public static SteamVR_Input_ActionSet_tracker tracker
        {
            get
            {
                return SteamVR_Actions.p_tracker.GetCopy<SteamVR_Input_ActionSet_tracker>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_oculus = ((SteamVR_Input_ActionSet_oculus)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_oculus>("/actions/oculus")));
            SteamVR_Actions.p_tracker = ((SteamVR_Input_ActionSet_tracker)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_tracker>("/actions/tracker")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.oculus,
                    SteamVR_Actions.tracker};
        }
    }
}
