//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_oculus : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftJoystick
        {
            get
            {
                return SteamVR_Actions.oculus_LeftJoystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonA
        {
            get
            {
                return SteamVR_Actions.oculus_ButtonA;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonB
        {
            get
            {
                return SteamVR_Actions.oculus_ButtonB;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrabGrip
        {
            get
            {
                return SteamVR_Actions.oculus_RightGrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonX
        {
            get
            {
                return SteamVR_Actions.oculus_ButtonX;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonY
        {
            get
            {
                return SteamVR_Actions.oculus_ButtonY;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrabPinch
        {
            get
            {
                return SteamVR_Actions.oculus_RightGrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightJoystickWest
        {
            get
            {
                return SteamVR_Actions.oculus_RightJoystickWest;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightJoystickEast
        {
            get
            {
                return SteamVR_Actions.oculus_RightJoystickEast;
            }
        }
    }
}
